/** @type {import('tailwindcss').Config} */
module.exports = {
	content: [
		"./src/**/*.{js,ts,jsx,tsx,mdx}",
	],
	theme: {
		screens: {
			'mobile-s': '400px',
			'mobile': '650px',
			'mobile-l': '750px',
			'tablet': '900px',
			'tablet-l': '1000px',
			'laptop': '1200px',
			'laptop-l': '1550px',
			'desktop': '1900px',
			'desktop-l': '2100px',
		},
		extend: {
			colors: {
				'accent': 'var(--accent-primary)',
				'charcoal': '#1E1E1E',
				'cyan-light': '#00FFFF',
				'cyan-x-light': '#E8F8F9',
				'cyan': '#00AEBC',
				'grey-dark': '#4D4D4D',
				'grey-light': '#CCCCCC',
				'grey-x-dark': '#333333',
				'grey-x-light': '#E6E6E6',
				'grey': '#808080',
				'midnight': '#161616',
				'navy-dark': '#21232D',
				'navy': '#2C324A',
				'off-white': '#F2F2F2',
				'red-faded': '#FFEFEF',
				'red-light': '#FF6B6B',
				'red': '#D30000',
				'white': '#FFFFFF',

				'section-bg': 'var(--section-bg)',
				'bg-accent-primary': 'var(--bg-accent-primary)',
				'bg-accent-secondary': 'var(--bg-accent-secondary)',
			},
			fontFamily: {
				logo: ['var(--font-logo)'],
				sans: ['var(--font-poppins)'],
				script: ['var(--font-script)'],
			},
			fontSize: {
				h1: 'var(--h1)',
				h2: 'var(--h2)',
				h3: 'var(--h3)',
				h4: 'var(--h4)',
				h5: 'var(--h5)',
				h6: 'var(--h6)',
				small: 'var(--font-small)',
				standard: 'var(--font-standard)',
				large: 'var(--font-large)',
				mega: 'var(--font-mega)',
				giga: 'var(--font-giga)',
				ludicrous: 'var(--font-ludicrous)',
			},
			fontWeight: {
				thin: 100,
				extralight: 200,
				light: 300,
				regular: 400,
				medium: 500,
				semibold: 600,
				bold: 700,
				extrabold: 800,
				black: 900,
			},
			spacing: {
				'gutter-large': 'var(--gutter-large)',
				'gutter-nav': 'var(--gutter-small)',
				'gutter-small': 'var(--gutter-small)',
				'gutter': 'var(--gutter-medium)',
				'section': 'var(--section-spacing)',
			},
		},
	},
	plugins: [],
}